header in shopping-list
Valik3201/bookshelf pull request #34
Opened 2023-12-27 16:28 UTC by tomekstanczak

Add:
in shopping-list-main.html -> <script src="/src/js/mobileMenu.js"></script>
all code in shopping-list-header.html
change arrow-right icon color in style.css

2023-12-27 17:56 UTC, Valik3201 requested changes
Proponuje jeszcze zmienić klasę `.home-link` oraz `.shopping-list-link `na np. `.nav-list__link` dla linku "HOME" i "SHOPPING LIST".

Dodatkowo dodać klasę `.nav-list__link--active` dla aktywnego linku, aby zaznaczyć, że jest on aktywny i w nim odpowiednio dodać ten żółty background. 😊

2023-12-27 17:56 UTC, Valik3201 commented on src/partials/shopping-list/shopping-list-main.html
> +<script src="/src/js/mobileMenu.js"></script>
Nie ma konieczności podłączania każdego skryptu oddzielnie; wszystko jest gromadzone w jednym głównym pliku index.js. W ten sposób wszystkie moduły są skonsolidowane i łatwiej zarządzać nimi.

Natomiast później podzielimy index.js na 2 pliki dla Home i Shopping List.

2023-12-27 17:56 UTC, Valik3201 commented on src/partials/shopping-list/shopping-list-header.html
> +            <a href="./shopping-list.html" class="shopping-list-link">SHOPPING LIST</a
Proponuję zamknąć tag `<a>` wokół tekstu "**SHOPPING LIST**" i ikony SVG, aby obejmował całą zawartość linku.

2023-12-27 18:08 UTC, Valik3201 commented
Dodaj jeszcze `stroke: #EAC645;` dla klasy `.arrow-right-icon` bo po aktualizacji ikonek jej nie widać 😁

2023-12-27 18:36 UTC, tomekstanczak commented on src/partials/shopping-list/shopping-list-main.html
> +<script src="/src/js/mobileMenu.js"></script>
ok, tylko nie działał skrypt, po załączeniu zaczął

2023-12-27 18:36 UTC, tomekstanczak commented on src/partials/shopping-list/shopping-list-header.html
> +            <a href="./shopping-list.html" class="shopping-list-link">SHOPPING LIST</a
tak, już robię

2023-12-29 20:38 UTC, Valik3201 approved these changes

2023-12-29 20:38 UTC, merged